#!/usr/bin/env python3
from latqcdtools.hisq_tools import impdist
import latqcdtools.logger as logger

Ns=56
eps=1e-5
lerror=False

''' Test file is generated by Olaf's improved distance code at Ns=56. '''
testfile=open('imptest.d','r') 
impdistlistcontrol=[]
for line in testfile:
  column=line.split()
  impdistlistcontrol.append(float(column[1]))

''' Caclulate tree-level improved distances. '''
impdistlist=impdist(Ns,int((Ns/2)**2))

''' The error checks. You shouldn't see any output. '''
rmax1=len(impdistlist)
rmax2=len(impdistlistcontrol)
if not rmax1==rmax2:
  print("        rmax1, rmax2 = ",rmax1,rmax2)
  logger.TBError("rmax1 != rmax2.")
for idist in range(rmax1):
  diff=abs(impdistlistcontrol[idist]-impdistlist[idist])
  if diff>=eps:
    logger.warn(" Suprising distance found at idist=",idist)
    print("          dcontrol, d, eps=",impdistlistcontrol[idist],impdistlist[idist],eps)
    lerror=True

testfile.close()
if lerror:
  logger.TBError("Some surprising distances found; check the output.")
else:
  logger.TBPass("Test passed!")
