import latqcdtools.logger as lg

def test_print():
    print('-------')
    lg.warn("WARN")
    lg.warn("Array: ",[1,2,3,4])
    lg.warn("Float: ",1.2)
    lg.warn("Int: ", 42)
    lg.info("INFO")
    lg.info("Array: ",[1,2,3,4])
    lg.info("Float: ",1.2)
    lg.info("Int: ", 42)
    lg.progress("PROGRESS")
    lg.progress("Array: ",[1,2,3,4])
    lg.progress("Float: ",1.2)
    lg.progress("Int: ", 42)
    lg.details("DETAILS")
    lg.details("Array: ",[1,2,3,4])
    lg.details("Float: ",1.2)
    lg.details("Int: ", 42)
    lg.debug("DEBUG")
    lg.debug("Array: ",[1,2,3,4])
    lg.debug("Float: ",1.2)
    lg.debug("Int: ", 42)
    print('-------')
